version: "3.9"
services:

mqtt:
image: eclipse-mosquitto:2
ports:
- "1883:1883"
api:
image: demo/api:latest
ports: ["8080:8080"]
db:
image: postgres:15
environment:
POSTGRES_PASSWORD: demo
web:
image: demo/web:latest
ports: ["3000:3000"]
Note: All services are commented out. This file illustrates topology only.
